config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root 'dashboard#index'
  get 'dashboard', to: 'dashboard#index'
  get 'profile', to: 'dashboard#profile'
  get ':id', to: 'dashboard#show', as: :user
  patch 'links/:id', to: 'links#update', as: :links
  post 'links', to: 'links#create', as: :create_links
  delete 'links/:id', to: 'links#destroy', as: :destroy_links
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_user, only: [:show]

  def index
    @should_render_navbar = true
  end

  def show
    if @user.nil?
      redirect_to dashboard_path
      return
    end
    @links = @user.links.where.not(url: '', title: '').order(created_at: :asc)
  end

  def profile
    @should_render_navbar = true
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  rescue StandardError
    @user = nil
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <h1 style="text-align: center">Your Links</h1>
      <%= button_to "New link", create_links_url, class: "btn btn-success btn-block mb-4 mt-3", style: "width: 100%" %>
      <% current_user.links.order(created_at: :asc).each do |link| %>
        <%= simple_form_for(link, url: links_url(link)) do |f| %>
          <%= f.input :title, placeholder: "Title", label: false, class: "form-control" %>
          <%= f.input :url, placeholder: "URL", label: false, class: "form-control" %>
          <%= f.submit "Update", class: "btn btn-primary me-auto mt-2" %>
        <% end %>
        <%= button_to "Delete", destroy_links_path(link), method: :delete, class: "delete-button btn btn-danger me-auto"  %>
      <% end %>
    </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/dashboard/profile.html.erb
<div class="container">
  <h1 style="text-align: center">Profile</h1>
  <%= simple_form_for(current_user, url: registration_path(current_user),
                      html: { method: :put }) do |f| %>
    <div class="row">
      <div class="col-6">
        <div class="row mt-5">
          <div class="col-6">
            <%= image_tag(current_user.avatar, class: "avatar-image") if current_user.avatar.attached? %>
          </div>
          <div class="col-6 mt-5">
            <%= f.input :avatar, required: false, label: false %>
          </div>
        </div>
        <div class="row mt-5">
          <div class="col-6 no-padding-col">
            <%= f.input :full_name, placeholder: "Full Name...", label: false, class: "form-control", required: false %>
          </div>
          <div class="col-6 no-padding-col">
            <div class="input-group mb-3" style="padding-left: 10px !important">
              <span class="input-group-text">@</span>
              <%= f.input :username, placeholder: "Username...", label: false, required: true %>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col no-padding-col">
            <div class="input-group row">
              <%= f.input :body, placeholder: "About you...", label: false, class: "form-control", required: false %>
            </div>
          </div>
        </div>
        <div class="col-4">
          <%= f.submit "Update Account", class: "btn btn-primary mt-3", style: "width: 100%" %>
        </div>
      </div>
      <div class="col-6">
        <div class="row profile-links" data-controller="clipboard" data-clipboard-success-content="Link Copied!">
            <%= hidden_field_tag(:share_link, user_url(current_user.friendly_id), data: { "clipboard-target": "source" }, readonly: true ) %>
<!--            <button onclick="alert('Link copied to clipboard!')" type="button" class="btn btn-outline-success" data-action="clipboard#copy" style="margin-bottom: 40px">-->
            <button type="button" class="btn btn-outline-success close" data-action="clipboard#copy" style="margin-bottom: 40px">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-share me-1" viewBox="0 0 16 16">
                <path d="M13.5 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5zm-8.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm11 5.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3z"/>
              </svg>
              <span data-clipboard-target="button">
                Share your Linktree
              </span>
            </button>
          <%= link_to "See your Linktree", current_user, class: "btn btn-outline-success" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboard/show.html.erb
<div class="profile-page">
  <div class="container">
    <div class="row">
      <div class="col-3"></div>
      <div class="col-6">
        <div class="row mt-5">
          <div class="col-12 d-flex justify-content-center">
            <%= image_tag(@user.avatar, class: "avatar-image") if @user.avatar.attached? %>
          </div>
          <div class="col-12 d-flex justify-content-center">
            <h2 class="white-font"><%= @user.full_name %></h2>
          </div>
          <div class="col-12 d-flex justify-content-center">
            <p class="white-font"><%= @user.body %></p>
          </div>
        </div>
      </div>
      <div class="col-3">
        <div class="row profile-links" data-controller="clipboard">
          <%= hidden_field_tag(:share_link, user_url(@user.friendly_id), data: { "clipboard-target": "source" }, readonly: true ) %>
          <button onclick="alert('Link copied to clipboard!')" type="button" class="share-button" data-action="clipboard#copy" style="margin-bottom: 40px">
            <span class="share-button-span">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-share me-1" viewBox="0 0 16 16">
                <path d="M13.5 1a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.499 2.499 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5zm-8.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm11 5.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3z"/>
              </svg>
            </span>
          </button>
        </div>
      </div>
      <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
          <% @links.each do |link| %>
            <div class="row">
              <div class="col-12 d-flex justify-content-center">
                <%= link_to link.url, target: "_blank", class: "linkable btn btn-secondary" do %>
                  <span class="linkable-span"><%= link.title %></span>
                <% end %>
              </div>
            </div>
          <% end %>
          <div class="row">
            <div class="col-12 d-flex justify-content-center logo-link-container">
              <%= link_to new_registration_path(@user), class: "text-white logo-link" do %>
                <h4>Linktree</h4>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-3"></div>
      </div>
    </div>
  </div>
</div>